version: '3.8'

services:
  python_app:
    image: python:3.10-slim
    container_name: python_app
    working_dir: /app
    volumes:
      - ../results:/app/results

  java_app:
    image: openjdk:17-slim
    container_name: java_app
    working_dir: /app
    volumes:
      - ../results:/app/results

  cpp_app:
    image: gcc:latest
    container_name: cpp_app
    working_dir: /app
    volumes:
      - ../results:/app/results

  javascript_app:
    image: node:18-alpine
    container_name: javascript_app
    working_dir: /app
    volumes:
      - ../results:/app/results

  go_app:
    image: golang:1.20-alpine
    container_name: go_app
    working_dir: /app
    volumes:
      - ../results:/app/results
