version: '3.8'

services:
  python_app:
    image: python:3.10-slim
    container_name: python_app
    working_dir: /app
    volumes:
      - ../Actividad-2_codigos/python:/app
      - ./results:/app/results
    command: ["python", "main.py"]

  java_app:
    image: openjdk:17-slim
    container_name: java_app
    working_dir: /app
    volumes:
      - ../Actividad-2_codigos/java:/app
      - ./results:/app/results
    command: sh -c "javac Main.java && java Main"

  cpp_app:
    image: gcc:latest
    container_name: cpp_app
    working_dir: /app
    volumes:
      - ../Actividad-2_codigos/cpp:/app
      - ./results:/app/results
    command: sh -c "g++ -o main main.cpp && ./main"

  javascript_app:
    image: node:18-alpine
    container_name: javascript_app
    working_dir: /app
    volumes:
      - ../Actividad-2_codigos/javascript:/app
      - ./results:/app/results
    command: ["node", "main.js"]

  go_app:
    image: golang:1.20-alpine
    container_name: go_app
    working_dir: /app
    volumes:
      - ../Actividad-2_codigos/go:/app
      - ./results:/app/results
    command: ["go", "run", "main.go"]
  benchmark_manager:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./results:/app/results
      - ../Actividad-2_codigos/benchmark:/app/
    command: ["python", "benchmark.py"]
    depends_on:
      - python_app
      - java_app
      - cpp_app
      - javascript_app
      - go_app