version: '3.8'

services:
  python_app:
    image: python:3.10-slim
    container_name: python_app
    working_dir: /app
    volumes:
      - ./results:/app/results
      - ../Actividad-2_codigos/python/main.py:/app/main.py
    command: ["python", "main.py"]

  java_app:
    image: openjdk:17-slim
    container_name: java_app
    working_dir: /app
    volumes:
      - ./results:/app/results
      - ../Actividad-2_codigos/java/Main.java:/app/Main.java

  cpp_app:
    image: gcc:latest
    container_name: cpp_app
    working_dir: /app
    volumes:
      - ./results:/app/results
      - ../Actividad-2_codigos/cpp/main.cpp:/app/main.cpp

  javascript_app:
    image: node:18-alpine
    container_name: javascript_app
    working_dir: /app
    volumes:
      - ./results:/app/results
      - ../Actividad-2_codigos/javascript/main.js:/app/main.js

  go_app:
    image: golang:1.20-alpine
    container_name: go_app
    working_dir: /app
    volumes:
      - ./results:/app/results
      - ../Actividad-2_codigos/go/main.go:/app/main.go
  results_collector:
    image: alpine
    container_name: results_collector
    working_dir: /app
    volumes:
      - ./results:/app/results
    command: ["/bin/sh", "-c", "sleep 5 && cat /app/results/results.txt | sort -k2 -n | awk '{printf \"%-15s %s ms\\n\", $1, $2}'"]
    depends_on:
      - python_app
      - java_app
      - cpp_app
      - javascript_app
      - go_app
